apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rxs7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rxs7
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rxs7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rxs7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rxs7
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dcrj-tenant/rhtap-demo-app/hacbs-test-project-rxs7@sha256:a269152547967c66488620375586a8c81fad8d0411bfc1e9ed797f79277be725
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
